[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/translate"
  to = "/.netlify/functions/translate"
  status = 200

[[redirects]]
  from = "/api/news/*"
  to = "/.netlify/functions/contentful-news"
  status = 200

[[redirects]]
  from = "/api/gallery"
  to = "/.netlify/functions/contentful-gallery"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://images.ctfassets.net https://assets.ctfassets.net https://downloads.ctfassets.net; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://images.ctfassets.net"
